- README.md
- cyclonedx/parser/__init__.py
- cyclonedx/parser/environment.py
- cyclonedx/parser/poetry.py
- cyclonedx/parser/requirements.py
- poetry.lock
- pyproject.toml
- tests/fixtures/poetry-lock-simple.txt
- tests/test_parser_poetry.py
We already support gleaning packages:
1. Installed in your current Python environment
2. Parsing of `requirements.txt` formatted files
This PR adds parsing support for `poetry.lock` files + some fixes discovered enroute.
> FEATURE: Adde poetry.lock parser support

- .github/workflows/docs.yml
- .gitignore
- README.md
- poetry.lock
- pyproject.toml
Signed-off-by: Patrick Dwyer <patrick.dwyer@owasp.org>
> Add initial doc generation and publishing

- cyclonedx/parser/conda.py
the docs say:
> Returns:
>            A `list` of `CondaPackage` instances parsed.
but the code does not state any return type.
and since the method is abstract, i looked at the implementations, and none of the two implementations has a return type.
instead, both implementations modify the class state via `self._conda_packages.append()`
> fixed typehints/docs in `_BaseCondaParser`

- .github/workflows/docs.yml
- .github/workflows/poetry.yml
- pyproject.toml
- tox.ini
> FEAT: Support Python 3.10

- cyclonedx/model/vulnerability.py
This fixes a small bug when constructing a `Vulnerability` model that eventually gets serialized to XML: `get_ratings` expects `self._ratings` to be a `List[VulnerabilityRating]` instead of an `Optional[...]`, so we default-initialize it if the constructor is passed `None`.
There are other type errors in the same constructor; I'll update this PR as I continue to try to get XML serialization working in `pip-audit`.
Downstream: https://github.com/trailofbits/pip-audit/pull/109
> model/vulnerability: fix optional type

- cyclonedx/utils/conda.py
- tests/test_utils_conda.py
Hopefully, this is the solution to the issue raised in #44, #51 and refined into #65.
@bollwyvl kindly provided an example Conda package URL that was breaking our parsing. This PR aims to make our parsing more robust and cater for the example provided.
> FIX: update Conda package parsing to handle `build` containing underscore

- poetry.lock
- pyproject.toml
see #44
also updated some locked dependencies: 
• Installing zipp (3.6.0)
• Updating backports.entry-points-selectable (1.1.0 -> 1.1.1)
• Updating distlib (0.3.3 -> 0.3.4)
• Installing importlib-metadata (4.8.2)
• Updating markdown (3.3.4 -> 3.3.6)
• Updating packaging (21.0 -> 21.3)
> feat: Loosed dependency versions to make this library more consumable

- poetry.lock
- pyproject.toml
- requirements.lowest.txt
> fix: removed requirements-parser as dependency (temp) as not available for Python 3 as Wheel

- .gitignore
- .readthedocs.yaml
- cyclonedx/model/__init__.py
- cyclonedx/model/vulnerability.py
- cyclonedx/output/json.py
- cyclonedx/output/serializer/json.py
- cyclonedx/output/xml.py
- docs/Makefile
- docs/architecture.rst
- docs/conf.py
- docs/index.rst
- docs/install.rst
- docs/make.bat
- docs/modelling.rst
- docs/outputting.rst
- docs/parsing.rst
- docs/requirements.txt
- docs/support.rst
- poetry.lock
- pyproject.toml
- tests/fixtures/bom_v1.4_setuptools_with_vulnerabilities.json
- tests/test_model.py
- tests/test_output_json.py
- tests/test_output_xml.py
As part of the overhaul for 1.4 schema, notable documentation changes are required and this seems like a sane time to migrate where we publish docs to.
Closes #119
> Move documentation to readthedocs.org

- cyclonedx/output/json.py
- tests/fixtures/bom_v1.2_setuptools.json
- tests/fixtures/bom_v1.3_setuptools.json
- tests/fixtures/bom_v1.3_toml_with_component_external_references.json
- tests/fixtures/bom_v1.3_toml_with_component_hashes.json
- tests/fixtures/bom_v1.3_toml_with_component_license.json
- tests/fixtures/bom_v1.4_setuptools.json
- tests/fixtures/bom_v1.4_setuptools_no_version.json
- tests/fixtures/bom_v1.4_setuptools_with_release_notes.json
- tests/fixtures/bom_v1.4_setuptools_with_vulnerabilities.json
> feat: add support for `$schema` in JSON output

- cyclonedx/model/bom.py
- cyclonedx/output/json.py
- cyclonedx/output/xml.py
- tests/fixtures/bom_v1.3_with_metadata_component.json
- tests/fixtures/bom_v1.3_with_metadata_component.xml
- tests/test_bom.py
- tests/test_e2e_environment.py
- tests/test_output_json.py
- tests/test_output_xml.py
> Add support for metadata component

- cyclonedx/model/component.py
- cyclonedx/output/xml.py
- tests/fixtures/bom_v1.0_setuptools_with_cpe.xml
- tests/fixtures/bom_v1.1_setuptools_with_cpe.xml
- tests/fixtures/bom_v1.2_setuptools_with_cpe.json
- tests/fixtures/bom_v1.2_setuptools_with_cpe.xml
- tests/fixtures/bom_v1.3_setuptools_with_cpe.json
- tests/fixtures/bom_v1.3_setuptools_with_cpe.xml
- tests/fixtures/bom_v1.4_setuptools_with_cpe.json
- tests/fixtures/bom_v1.4_setuptools_with_cpe.xml
- tests/test_output_json.py
- tests/test_output_xml.py
Setting CPE was missing for component, now it is possible to set CPE and output CPE for a component.
fixes #139
> feat: add CPE to component

- cyclonedx/model/component.py
- cyclonedx/model/vulnerability.py
- docs/modelling.rst
- tests/fixtures/bom_v1.3_with_metadata_component.json
- tests/fixtures/bom_v1.3_with_metadata_component.xml
- tests/test_model_component.py
- tests/test_model_vulnerability.py
- tests/test_output_json.py
- tests/test_output_xml.py
Updated logic to ensure `bom-ref` for Component and Vulnerability have a unique value if not programmatically supplied. We are using a UUIDv4.
Closes #141
> feat: `bom-ref` for Compomnent and Vulnerability default to a UUID

- cyclonedx/model/__init__.py
- cyclonedx/model/bom.py
- cyclonedx/model/component.py
- cyclonedx/model/issue.py
- cyclonedx/model/release_note.py
- cyclonedx/model/service.py
- cyclonedx/model/vulnerability.py
- tests/test_model.py
> BREAKING CHANGE: adopted PEP-3102 for model classes

- cyclonedx/model/bom.py
- cyclonedx/output/json.py
- cyclonedx/output/schema.py
- cyclonedx/output/xml.py
- tests/base.py
- tests/data.py
- tests/fixtures/json/1.2/bom_with_full_metadata.json
- tests/fixtures/json/1.3/bom_with_full_metadata.json
- tests/fixtures/json/1.4/bom_with_full_metadata.json
- tests/fixtures/xml/1.2/bom_with_full_metadata.xml
- tests/fixtures/xml/1.3/bom_with_full_metadata.xml
- tests/fixtures/xml/1.4/bom_with_full_metadata.xml
fix: JSON comparison in unit tests was broken
chore: corrected some source license headers
Closes: #6
> feat: support complete model for `bom.metadata`

- .isort.cfg
- CONTRIBUTING.md
- cyclonedx/model/__init__.py
- cyclonedx/model/bom.py
- cyclonedx/model/bom_ref.py
- cyclonedx/model/component.py
- cyclonedx/model/issue.py
- cyclonedx/model/release_note.py
- cyclonedx/model/service.py
- cyclonedx/model/vulnerability.py
- cyclonedx/output/json.py
- cyclonedx/output/serializer/json.py
- cyclonedx/output/xml.py
- poetry.lock
- pyproject.toml
- tests/base.py
- tests/data.py
- tests/test_bom.py
- tests/test_component.py
- tests/test_e2e_environment.py
- tests/test_model.py
- tests/test_model_component.py
- tests/test_model_issue.py
- tests/test_model_release_note.py
- tests/test_model_service.py
- tests/test_model_vulnerability.py
- tests/test_output_generic.py
- tests/test_output_json.py
- tests/test_output_xml.py
- tox.ini
fixes #85
* added QA tool: `isort`
* added QA tests: `flake8-isort`
* applied `isort` to all code, so  imports are sorted
> style: sort imports

- cyclonedx/output/__init__.py
error output was hard to read, because no info was given which file/dir was causing the issue.
fixed it: error objects now have the dir/file path as a message.
> feat: output errors are verbose

- cyclonedx/output/json.py
> fix: `version` being optional in JSON output can raise error

- poetry.lock
- pyproject.toml
- requirements.lowest.txt
To be able to use new types, which will be introduced in Python 3.11, the package version shouldn't be pinned to `3.10.x` and the package can be installed with any Python version, because you can't know, what the user will use. Here is the official explanation on version pinning
> Starting with version 4.0.0, typing_extensions uses [Semantic Versioning](https://semver.org/). The major version is incremented for all backwards-incompatible changes. Therefore, it’s safe to depend on typing_extensions like this: typing_extensions >=x.y, <(x+1), where x.y is the first version that includes all features you need.
> feat(deps): remove unused `typing-extensions` constraints

- .github/workflows/deploy.yml
see also: https://github.com/relekang/python-semantic-release/issues/442
> ci: pin GH-action `semantic-release` to v7.28.1

- cyclonedx/model/__init__.py
- cyclonedx/model/bom.py
- cyclonedx/model/component.py
- cyclonedx/model/dependency.py
- cyclonedx/model/issue.py
- cyclonedx/model/release_note.py
- cyclonedx/model/service.py
- cyclonedx/model/vulnerability.py
show what would happen, if the unnecessary type cast of `set`/`SortedSet` was omitted.
unnecessary on runtime (as all unit/functional/integration tests are passing), 
but `mypy` is not able to detect that the setter has a _wider_ type definition than the getter... 
see the issue https://github.com/python/mypy/issues/3004 
and the decision that the issue is a feature-lack/bug: https://github.com/python/mypy/issues/3004#issuecomment-562073403
this PR is intended to last for a while and be rebased, whenever needed, 
to test if mypy implemented the missing feature, some day.
> feat: reduce unnessessarry type casting of `set`/`SortedSet` when useing setter

- .github/workflows/poetry.yml
- .pre-commit-config.yaml
- README.md
- cyclonedx/model/bom.py
- cyclonedx/model/bom_ref.py
- cyclonedx/model/component.py
- cyclonedx/output/json.py
- cyclonedx/output/xml.py
- docs/index.rst
- docs/schema-support.rst
- tests/base.py
- tests/data.py
- tests/test_model_bom.py
- tests/test_model_component.py
> feat: change model to put `Vulnerability` at `Bom` level, not `Component` level

- cyclonedx/model/bom.py
- tests/test_model_bom.py
feat: allow `version` of BOM to be defined
feat: allow `serial_number` of BOM to be prescribed
feat: add helper method to get URN for a BOM according to https://www.iana.org/assignments/urn-formal/cdx
Signed-off-by: Paul Horton <paul.horton@owasp.org>
> adding helper methods to allow easier support for `BomLink`

- tox.ini
poetry install is currently broken
see https://github.com/CycloneDX/cyclonedx-python-lib/actions/runs/2982471109
this PR intents to address this.
> chore: fix poetry in tox

- .gitignore
- cyclonedx/exception/factory.py
- cyclonedx/factory/__init__.py
- cyclonedx/factory/license.py
- cyclonedx/spdx.py
- poetry.lock
- pyproject.toml
- tests/test_factory_license.py
- tests/test_spdx.py
fixes #304
related docs: 
- SPDX expression spec: https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/
- SPDX ids supported by CycloneDX: https://github.com/CycloneDX/specification/blob/master/schema/spdx.schema.json 
----
---- 
besides the new implementation and the new tests, the following changed: 
- poetry mentioned an outdated lock so i ran `poetry lock --no-update`
- had to run `poetry add --dev ddt`
- used poetry1.2
- and since all of this caused a lot of failing CI, i handcrafted the poetry lockfile
> feat: license factories

- cyclonedx/model/bom.py
- tests/test_component.py
- tests/test_model_bom.py
Signed-off-by: gruebel <anton.gruebel@gmail.com>
- adjusted the type hint for `get_component_by_purl` and added a test for it 🙂 
- changed the list/filter expression to use a list comprehension, which is almost 2x faster in this case 🚀
> fix: type hint for get_component_by_purl is incorrect

- .github/workflows/poetry.yml
github changed the latest ubuntu version.
that ubuntu version might not support py36 properly, therefore a fix was prepared
> ci: fix py36

- pyproject.toml
fixes https://github.com/CycloneDX/cyclonedx-python-lib/issues/336#issuecomment-1380688129
poetry will detect the `LICENSE` file automatically and put it in the bundle somewhere.
so we are still good, when we dont pack it in the root explicitly.
> chore: do not ship exra LICENSE file

- .github/workflows/deploy.yml
- .github/workflows/poetry.yml
- poetry.lock
- pyproject.toml
- requirements.lowest.txt
- tests/test_output_xml.py
- tox.ini
> feat: Support for Python 3.11

- .isort.cfg
- CONTRIBUTING.md
- tests/test_model_component.py
- tests/test_output_json.py
- tests/test_output_xml.py
- tox.ini
* made components' version optional in tests
* added some config for isort and flake8
> tests: compoennt versions optional

- cyclonedx/model/bom.py
The warning message lacks a space:
```
Lib\site-packages\cyclonedx\model\bom.py:569: UserWarning: The Component this BOM is describing None has no defined dependencies which means the Dependency Graph is incomplete - you should add direct dependencies to this Componentto complete the Dependency Graph data.
```
see `Componentto`.
> fix: add missing space in warning message

- cyclonedx/model/bom.py
- cyclonedx/model/component.py
- cyclonedx/serialization/__init__.py
- deps.lowest.r
- poetry.lock
- pyproject.toml
- tests/data.py
- tests/test_component.py
Originally I juste wanted to update `packageurl` with the added type hints to remove the type ignores, I also found a typing issue in `cyclonedx/serialization/__init__.py` but I couldn't upgrade the `poertry.lock` file, so I had to use the latest 1.4.1 version and they changed the lock file version to 2.0, which looks now different. This probably also the reason, why all the dependabot PRs are failing 🤔
> chore(deps): update poetry and other dependency versions

- .isort.cfg
- cyclonedx/model/bom.py
- cyclonedx/model/dependency.py
- tests/data.py
- tests/fixtures/json/1.4/bom_with_dependencies_hanging.json
- tests/fixtures/xml/1.4/bom_with_dependencies_hanging.xml
- tests/test_deserialize_xml.py
- tests/test_output_json.py
- tests/test_output_xml.py
the warning was shown when all was correct, 
but was omitted when it should have been shown ...
> fix: conditional warning if no root dependencies were found

- cyclonedx/spdx.py
- poetry.lock
- pyproject.toml
- tests/test_spdx.py
SPDX license expression detection should be feature-complete now, 
thanks to utilizing [nexB's license-expression library](https://github.com/nexB/license-expression).
This affects:
* `spdx.is_compound_expression()`
* `factory.license.LicenseChoiceFactory.make_from_string()`
* `factory.license.LicenseChoiceFactory.make_with_compound_expression()`.
----
fixes #424
> feat: complete SPDX license expression detection

- cyclonedx/factory/license.py
- tests/test_factory_license.py
> fix: `LicenseChoiceFactory.make_from_string()` prioritize SPDX id over expression

- .github/workflows/python.yml
- README.md
> chore: publish coverage report to codacy

- cyclonedx/exception/model.py
- cyclonedx/model/bom.py
- tests/data.py
- tests/test_model_bom.py
- tests/test_validation.py
If a LicenseExpression is set, then there must be no other license.
fixes #453
> fix: `bom.validate()` detects invalid license constellations

- cyclonedx/output/__init__.py
- cyclonedx/validation/__init__.py
- cyclonedx/validation/json.py
- cyclonedx/validation/model.py
- cyclonedx/validation/schema.py
- cyclonedx/validation/xml.py
- examples/complex.py
- tests/test_output.py
- tests/test_validation_json.py
- tests/test_validation_schema.py
- restructured validators, to enable possible non-schema-based validation. 
- optimized `validation.schema.get_instance()`
- optimized `output.get_instance()`
> refactor: schema based validator

- cyclonedx/spdx.py
- tests/test_spdx.py
caused by https://github.com/CycloneDX/cyclonedx-python/issues/598
> fix: SPDX-expression-validation internal crashes are cought and handled

- pyproject.toml
prevent parse issue like https://github.com/CycloneDX/cyclonedx-python-lib/network/updates/740004978
> chore: make `pypoject` parsable by dependabot

- cyclonedx/output/__init__.py
- examples/complex.py
- tests/test_deserialize_json.py
- tests/test_deserialize_xml.py
> bc: remove const `output.LATEST_SUPPORTED_SCHEMA_VERSION`

- cyclonedx/model/__init__.py
- tests/_data/models.py
- tests/_data/snapshots/get_bom_for_issue_497_urls-1.0.xml.bin
- tests/_data/snapshots/get_bom_for_issue_497_urls-1.1.xml.bin
- tests/_data/snapshots/get_bom_for_issue_497_urls-1.2.json.bin
- tests/_data/snapshots/get_bom_for_issue_497_urls-1.2.xml.bin
- tests/_data/snapshots/get_bom_for_issue_497_urls-1.3.json.bin
- tests/_data/snapshots/get_bom_for_issue_497_urls-1.3.xml.bin
- tests/_data/snapshots/get_bom_for_issue_497_urls-1.4.json.bin
- tests/_data/snapshots/get_bom_for_issue_497_urls-1.4.xml.bin
- tests/test_deserialize_json.py
- tests/test_deserialize_xml.py
fixes https://github.com/CycloneDX/cyclonedx-python-lib/issues/497
> feat: `model.XsUri` migrate control characters according to spec

- cyclonedx/model/bom_ref.py
- cyclonedx/output/__init__.py
- cyclonedx/serialization/__init__.py
- tests/_data/models.py
- tests/_data/snapshots/get_bom_with_nested_services-1.2.json.bin
- tests/_data/snapshots/get_bom_with_nested_services-1.2.xml.bin
- tests/_data/snapshots/get_bom_with_nested_services-1.3.json.bin
- tests/_data/snapshots/get_bom_with_nested_services-1.3.xml.bin
- tests/_data/snapshots/get_bom_with_nested_services-1.4.json.bin
- tests/_data/snapshots/get_bom_with_nested_services-1.4.xml.bin
- tests/_data/snapshots/get_bom_with_nested_services-1.5.json.bin
- tests/_data/snapshots/get_bom_with_nested_services-1.5.xml.bin
- tests/test_deserialize_json.py
- tests/test_deserialize_xml.py
- tests/test_enums.py
- tests/test_model_component.py
- tests/test_model_service.py
- tests/test_model_vulnerability.py
- tests/test_output_json.py
- tests/test_output_xml.py
> `BomRef`   default null

- cyclonedx/model/__init__.py
- tests/test_model.py
new API: `model.HashType.from_hashlib_alg()`
fixes https://github.com/CycloneDX/cyclonedx-python-lib/issues/518
> feat: add function to map python `hashlib` algorithms to CycloneDX

- pyproject.toml
raised dependency constraint for `py-serializable` to allow v1.0
> feat: support `py-serializable` v1.0

- cyclonedx/validation/xml.py
It would warn about missing xml validation and suggest installing the json-validation extra instead of the xml one.
Fix by suggesting the correct extra.
> fix: wrong extra name for xml validation

- tests/__init__.py
- tests/test_validation_json.py
- tests/test_validation_xml.py
When packaging cyclonedx-python-lib for a Linux distribution, it’s pretty common that [some JSON validation tests fail](https://aur.archlinux.org/cgit/aur.git/diff/PKGBUILD?h=python-cyclonedx-lib&id=9c6ae556874a633a521407a77a9a85bb31da2047).
Due to the large number of combinations and the fact that these tests are consecutively numbered, it has been tedious to figure out which tests are exactly failing and why.  
This in turn makes it difficult to decide which tests to disable or report upstream.
This PR appends meaningful names to validation tests so that instead of e.g.:
[…]::TestJsonValidator::test_validate_no_none_001
[…]::TestJsonValidator::test_validate_no_none_002
[…]::TestJsonValidator::test_validate_no_none_003
[…]::TestJsonValidator::test_validate_no_none_004 …
> tests: meaningful names to validation tests

- cyclonedx/model/license.py
- tests/_data/models.py
- tests/_data/snapshots/get_bom_with_licenses-1.1.xml.bin
- tests/_data/snapshots/get_bom_with_licenses-1.2.json.bin
- tests/_data/snapshots/get_bom_with_licenses-1.2.xml.bin
- tests/_data/snapshots/get_bom_with_licenses-1.3.json.bin
- tests/_data/snapshots/get_bom_with_licenses-1.3.xml.bin
- tests/_data/snapshots/get_bom_with_licenses-1.4.json.bin
- tests/_data/snapshots/get_bom_with_licenses-1.4.xml.bin
- tests/_data/snapshots/get_bom_with_licenses-1.5.json.bin
- tests/_data/snapshots/get_bom_with_licenses-1.5.xml.bin
- tests/_data/snapshots/get_bom_with_licenses-1.6.json.bin
- tests/_data/snapshots/get_bom_with_licenses-1.6.xml.bin
fixes #590
- renamed class `LicenseExpressionAcknowledgement` to `LicenseAcknowledgement`
- added _deprecated_ alias `LicenseExpressionAcknowledgement` for `LicenseAcknowledgement`  
so there is no breaking change
- added property `DisjunctiveLicense.acknowledgement`
- added integration test for new properties and structures
> feat: disjunctive license acknowledgement

- cyclonedx/factory/license.py
- cyclonedx/model/license.py
- tests/test_factory_license.py
add a parameter to `LicenseFactory.make_*()` methods, to set the `LicenseAcknowledgement`.
fixes #592
> feat: license factory set `acknowledgement`

- cyclonedx/schema/_res/README.md
- cyclonedx/schema/_res/bom-1.2-strict.SNAPSHOT.schema.json
- cyclonedx/schema/_res/bom-1.3-strict.SNAPSHOT.schema.json
- cyclonedx/schema/_res/bom-1.4.SNAPSHOT.schema.json
- cyclonedx/schema/_res/bom-1.5.SNAPSHOT.schema.json
- tests/_data/own/json/1.2/bom_with_mixed_licenses.json
- tests/_data/own/json/1.3/bom_with_mixed_licenses.json
- tests/test_deserialize_json.py
- tests/test_validation_json.py
- tests/test_validation_xml.py
- tools/schema-downloader.py
fixes https://github.com/CycloneDX/cyclonedx-python-lib/issues/612
> fix: json validation allow arbitrary `$schema`  value

- cyclonedx/model/contact.py
- tests/_data/own/json/1.4/empty-supplier.json
- tests/_data/own/json/1.4/empty_supplier.json
- tests/test_deserialize_json.py
> fix: allow suppliers with empty-string names

- cyclonedx/model/__init__.py
- tests/_data/models.py
- tests/_data/own/xml/1.6/regression_issue630.xml
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.0.xml.bin
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.1.xml.bin
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.2.json.bin
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.2.xml.bin
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.3.json.bin
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.3.xml.bin
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.4.json.bin
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.4.xml.bin
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.5.json.bin
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.5.xml.bin
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.6.json.bin
- tests/_data/snapshots/get_bom_for_issue_630_empty_property-1.6.xml.bin
- tests/test_real_world_examples.py
`cyclonedx.model.Property.value` value is optional, in accordance with the spec.
fixes #630
> fix: `cyclonedx.model.Property.value` value is optional

- cyclonedx/model/__init__.py
- cyclonedx/model/bom.py
- cyclonedx/model/component.py
- cyclonedx/model/contact.py
- cyclonedx/model/crypto.py
- cyclonedx/model/issue.py
- cyclonedx/model/license.py
- cyclonedx/model/release_note.py
- cyclonedx/model/service.py
- cyclonedx/model/vulnerability.py
this should make future PR reviews easier, since adding new args in the middle will not cause complete code blocks to change, but is just a new line ...
> style: model args - one per line

- cyclonedx/model/vulnerability.py
- tests/_data/models.py
- tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.5.json.bin
- tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.5.xml.bin
- tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.6.json.bin
- tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.6.xml.bin
- tests/test_model_vulnerability.py
Property `workaround` was missing from the vulnerability model. It was added in spec v1.5 and was marked as TODO before.
This is my first contribution on this project so if I done something wrong, just say me :smiley:
> feat: add workaround property for v1.5 and v1.6

- cyclonedx/model/__init__.py
- cyclonedx/model/component.py
- cyclonedx/model/contact.py
- cyclonedx/model/issue.py
- cyclonedx/model/license.py
- cyclonedx/model/release_note.py
- cyclonedx/model/service.py
- cyclonedx/model/vulnerability.py
- pyproject.toml
> fix: XML serialize `normalizedString` and `token` properly

- cyclonedx/model/__init__.py
- tests/test_model.py
The code mistreated hashes for Blake2b and SHA3.
Code for explicitly handling SHA1 & BLAKE3 was added, as those have no variants defined in the CycloneDX specification.
fixes #652
> feat: `HashType.from_composite_str` for Blake2b, SHA3, Blake3

- cyclonedx/model/license.py
> refactor!: `LicenseExpression()` optional args are named args

- cyclonedx/builder/this.py
- pyproject.toml
- tests/__init__.py
- tests/test_builder_this.py
QA for https://github.com/CycloneDX/cyclonedx-python-lib/pull/649
> tests: test builder this

- cyclonedx/model/bom.py
- cyclonedx/model/tool.py
- cyclonedx/model/vulnerability.py
- docs/upgrading.rst
- tests/_data/models.py
- tests/test_deserialize_xml.py
- tests/test_model_tool_repository.py
Item class of repository is to be called in singular(`Tool`).
> rename `ToolsRepository` -> `ToolRepository`

- cyclonedx/model/crypto.py
- tests/_data/own/json/1.6/issue690.json
- tests/test_deserialize_json.py
> fix: behavior of and typing for crypto setters with optional values

- docs/outputting.rst
[v6](https://github.com/CycloneDX/cyclonedx-python-lib/releases/tag/v6.0.0) API change removed deprecated function `output.get_instance()` (via #493) to use the function `output.make_outputter()` instead.
This PR updates the documentation as suggested by @jkowalleck in #702.
fixes #702
> docs: fix code examples regarding outputting

- cyclonedx/_internal/bom_ref.py
- cyclonedx/model/bom.py
- cyclonedx/model/definition.py
- tests/_data/models.py
- tests/_data/snapshots/get_bom_with_definitions_standards-1.0.xml.bin
- tests/_data/snapshots/get_bom_with_definitions_standards-1.1.xml.bin
- tests/_data/snapshots/get_bom_with_definitions_standards-1.2.json.bin
- tests/_data/snapshots/get_bom_with_definitions_standards-1.2.xml.bin
- tests/_data/snapshots/get_bom_with_definitions_standards-1.3.json.bin
- tests/_data/snapshots/get_bom_with_definitions_standards-1.3.xml.bin
- tests/_data/snapshots/get_bom_with_definitions_standards-1.4.json.bin
- tests/_data/snapshots/get_bom_with_definitions_standards-1.4.xml.bin
- tests/_data/snapshots/get_bom_with_definitions_standards-1.5.json.bin
- tests/_data/snapshots/get_bom_with_definitions_standards-1.5.xml.bin
- tests/_data/snapshots/get_bom_with_definitions_standards-1.6.json.bin
- tests/_data/snapshots/get_bom_with_definitions_standards-1.6.xml.bin
- tests/test_model_definition.py
This PR is addressing #697 and adding the [`bom.definitions`](https://cyclonedx.org/docs/1.6/json/#definitions) support.
I've intentionally left the [`bom.definitions.standards.signature`](https://cyclonedx.org/docs/1.6/json/#definitions_standards_items_signature) out since the entire data structure elsewhere is also missing.
[`bom.definitions.standards.requirements`](https://cyclonedx.org/docs/1.6/json/#definitions_standards_items_requirements) and
[`bom.definitions.standards.levels`](https://cyclonedx.org/docs/1.6/json/#definitions_standards_items_levels) are also left out and will be included with a latter PR #713 
fixes #697
is part of #696
> feat: add basic support for Definitions 

- cyclonedx/_internal/bom_ref.py
- cyclonedx/model/component.py
- cyclonedx/model/contact.py
- cyclonedx/model/service.py
- cyclonedx/model/vulnerability.py
- tests/test_internal/__init__.py
- tests/test_internal/test_bom_ref.py
> refactor: reuse internal helper `bom_ref_from_str`

- cyclonedx/model/__init__.py
- cyclonedx/model/bom.py
- tests/test_model.py
- tests/test_model_bom.py
> feat: add factory method `XsUri.make_bom_link()`

- .pre-commit-config.yaml
- cyclonedx/model/bom.py
- tests/test_model_bom.py
Adds a condition to check if the root component is the only component and then doesn't issue the warning. Closes #617
> fix: no warning for missing dependencies if no component exists

- cyclonedx/model/component.py
- cyclonedx/model/contact.py
- cyclonedx/model/definition.py
- cyclonedx/model/service.py
- cyclonedx/model/vulnerability.py
the auto-assigning `UUITv4` was removed in a breaking change in v6.0.0 . 
> * Object `model.bom_ref.BomRef`&#39;s property `value` defaults to `Null`, was arbitrary `UUID` ([#504] via [#505])
this fix aligns the docs.
> docs: remove invalid docsting note about auto-assigned `bom-ref` values

- cyclonedx/model/bom.py
- cyclonedx/model/bom_ref.py
- cyclonedx/model/component.py
- cyclonedx/model/contact.py
- cyclonedx/model/crypto.py
- cyclonedx/model/definition.py
- cyclonedx/model/dependency.py
- cyclonedx/model/license.py
- cyclonedx/model/service.py
- cyclonedx/model/vulnerability.py
- cyclonedx/serialization/__init__.py
Deprecates `.serialization.BomRefHelper` and `.serialization.LicenseRepositoryHelper`
fixes #756
> feat: couple classes and their serializes

- README.md
- docs/index.rst
- docs/install.rst
- docs/responsibilities_capabilities.rst
fixes #485
closes #719
docs preview: https://cyclonedx-python-library.readthedocs.io/en/docs-responsibilitis_capabilities/
> docs: responsibilities & capabilities

- cyclonedx/model/contact.py
- tests/_data/own/json/1.6/issue764.json
- tests/test_deserialize_json.py
fixes https://github.com/CycloneDX/cyclonedx-python-lib/issues/764
> feat: allow empty `OrganizationalEntity` object

- cyclonedx/model/contact.py
- tests/_data/own/json/1.6/issue771.json
- tests/test_deserialize_json.py
fixes https://github.com/CycloneDX/cyclonedx-python-lib/issues/771
> feat: allow empty `OrganizationalContact` object

- cyclonedx/model/__init__.py
- cyclonedx/model/bom.py
- cyclonedx/model/bom_ref.py
- cyclonedx/model/component.py
- cyclonedx/model/contact.py
- cyclonedx/model/crypto.py
- cyclonedx/model/definition.py
- cyclonedx/model/dependency.py
- cyclonedx/model/impact_analysis.py
- cyclonedx/model/issue.py
- cyclonedx/model/license.py
- cyclonedx/model/lifecycle.py
- cyclonedx/model/release_note.py
- cyclonedx/model/service.py
- cyclonedx/model/tool.py
- cyclonedx/model/vulnerability.py
- cyclonedx/schema/schema.py
- cyclonedx/serialization/__init__.py
- pyproject.toml
bump to `py-serializable` v2.0.0: <https://github.com/madpah/serializable/releases/tag/v2.0.0>
This is considered a breaking change, as downstream users might rely on the same package's previous version.
> chore(deps)!: `py-serializable==^1.1.1` -> `^2.0.0`

- cyclonedx/model/crypto.py
- cyclonedx/schema/_res/bom-1.6.SNAPSHOT.xsd
- tests/_data/models.py
- tests/_data/snapshots/get_bom_for_issue_692_components-1.0.xml.bin
- tests/_data/snapshots/get_bom_for_issue_692_components-1.1.xml.bin
- tests/_data/snapshots/get_bom_for_issue_692_components-1.2.json.bin
- tests/_data/snapshots/get_bom_for_issue_692_components-1.2.xml.bin
- tests/_data/snapshots/get_bom_for_issue_692_components-1.3.json.bin
- tests/_data/snapshots/get_bom_for_issue_692_components-1.3.xml.bin
- tests/_data/snapshots/get_bom_for_issue_692_components-1.4.json.bin
- tests/_data/snapshots/get_bom_for_issue_692_components-1.4.xml.bin
- tests/_data/snapshots/get_bom_for_issue_692_components-1.5.json.bin
- tests/_data/snapshots/get_bom_for_issue_692_components-1.5.xml.bin
- tests/_data/snapshots/get_bom_for_issue_692_components-1.6.json.bin
- tests/_data/snapshots/get_bom_for_issue_692_components-1.6.xml.bin
- tests/test_deserialize_json.py
applied the fix recommended in the thread.
added testcase and BOM json from the mentioned issue.
fixes #692
> feat: add `cyclonedx.model.crypto.ProtocolProperties.crypto_refs`

- tests/test_spdx.py
> tests: revisit `spdx.is_expression()`

- CONTRIBUTING.md
supersedes https://github.com/CycloneDX/cyclonedx-python-lib/pull/773/files#r1954324461
> docs:  extended instructions for "contributing"

- cyclonedx/model/__init__.py
- cyclonedx/model/component.py
- cyclonedx/model/issue.py
- cyclonedx/model/vulnerability.py
- tests/test_model.py
- tests/test_model_component.py
- tests/test_model_issue.py
the following classes' init no longer raise  `NoPropertiesProvidedException`:
* `cyclonedx.model.IdentifiableAction`
* `cyclonedx.model.component.Commit`
* `cyclonedx.model.component.ComponentEvidence`
* `cyclonedx.model.component.Diff`
* `cyclonedx.model.component.Pedigree`
* `cyclonedx.model.issue.IssueTypeSource`
* `cyclonedx.model.vulnerability.VulnerabilityAnalysis`
* `cyclonedx.model.vulnerability.VulnerabilityCredits`
* `cyclonedx.model.vulnerability.VulnerabilityRating`
* `cyclonedx.model.vulnerability.VulnerabilitySource`
----
did a global search and found these file/classes
raising this exception
File                -      Class
model/__init__.py   - IdentifiableAction
model/component.py  - Commit
model/component.py  - ComponentEvidence
model/component.py  - Diff …
> feat: avoid raising `NoPropertiesProvidedException` for optional parameters

- cyclonedx/model/vulnerability.py
- tests/_data/models.py
- tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.5.json.bin
- tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.5.xml.bin
- tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.6.json.bin
- tests/_data/snapshots/get_bom_with_component_setuptools_with_vulnerability-1.6.xml.bin
fixed: #791 
add first_issued and last_updated to VulnerabilityAnalysis, update test to verify this
> feat: VulnerabilityAnalysis properties for issued/updated datetime

- cyclonedx/model/vulnerability.py
- tests/test_model_vulnerability.py
When trying to generate a CycloneDX BOM that has two vulnerabilities that only differ in their analysis, you get
```
TypeError: '<' not supported between instances of 'VulnerabilityAnalysis' and 'VulnerabilityAnalysis'
```
This PR adds the `__lt__` method for the VulnerabilityAnalysis model to fix sorting and also includes a test case to verify the fix.
> fix: Add missing comparator for VulnerabilityAnalysis

- .github/workflows/python.yml
- CONTRIBUTING.md
- cyclonedx/_internal/compare.py
- cyclonedx/spdx.py
- cyclonedx/validation/__init__.py
- pyproject.toml
- tests/__init__.py
- tests/test_deserialize_xml.py
- tests/test_enums.py
- tests/test_validation_json.py
- tests/test_validation_xml.py
- tools/schema-downloader.py
- tox.ini
- typings/sortedcontainers.pyi
- followup of #809
- add pyupgrade tooling and tests
- apply pyupgraded code style
> style: pyupgrade 3.9

- cyclonedx/validation/json.py
- cyclonedx/validation/xml.py
- examples/complex_deserialize.py
- examples/complex_serialize.py
part of 
-  #827
in preparation for 
- #836
> feat: validators return specific error classes

- .github/workflows/python.yml
- .github/workflows/release.yml
- pyproject.toml
- tox.ini
> chore: dependency tests in CI/CT
