cyclonedx/model/component.py
=> fix: whitespace on empty line removed

.github/workflows/poetry.yml, .mypy.ini, cyclonedx/model/bom.py, cyclonedx/output/json.py, cyclonedx/parser/environment.py, cyclonedx/utils/conda.py, pyproject.toml, requirements.lowest.txt, tests/test_parser_environment.py, tox.ini
setup to test lowest possible requirements, while still being able to test the locked/pinned dev-dependencies
caused by #44
=> add tox env for minimal required dependencies

cyclonedx/parser/environment.py, pyproject.toml, requirements.lowest.txt
PR that aims to lower/relax our dependency versions as pointed in #44.
=> feat: lowering minimum dependency versions

poetry.lock, pyproject.toml, requirements.lowest.txt
=> fix: tightened dependency `packageurl-python`

CONTRIBUTING.md, poetry.lock, pyproject.toml
=> chore: bump `flake8` to v4 and add `autopep8`

.github/workflows/docs.yml, doc/requirements.txt
Attempt to resolve dependency conflict for building documentation introduced by #93.
Resolves:
- #106
=> fix: isolated dependencies for building documentation

.github/workflows/poetry.yml
=> chore: disable poetry-cache in gh-workflow

README.md, docs/install.rst, docs/processes/release/conda-forge.md
after the anaconda release was announced (see https://github.com/CycloneDX/cyclonedx-python-lib/issues/44#issuecomment-989912153)
we might need a shield for this.
here is the shield & some docs
=> DOCS: describe anaconda release process

poetry.lock, pyproject.toml
=> chore: bump dependencies

cyclonedx/model/__init__.py, cyclonedx/model/bom.py, cyclonedx/model/component.py, cyclonedx/model/issue.py, cyclonedx/model/release_note.py, cyclonedx/model/service.py, cyclonedx/model/vulnerability.py, cyclonedx/output/json.py, cyclonedx/output/schema.py, cyclonedx/output/serializer/__init__.py, cyclonedx/output/serializer/json.py, cyclonedx/output/xml.py, tests/data.py, tests/fixtures/json/1.2/bom_setuptools_complete.json, tests/fixtures/json/1.3/bom_setuptools_complete.json, tests/fixtures/json/1.4/bom_setuptools_complete.json, tests/fixtures/xml/1.0/bom_setuptools_complete.xml, tests/fixtures/xml/1.1/bom_setuptools_complete.xml, tests/fixtures/xml/1.2/bom_setuptools_complete.xml, tests/fixtures/xml/1.3/bom_setuptools_complete.xml, tests/fixtures/xml/1.4/bom_setuptools_complete.xml, tests/test_model.py, tests/test_model_component.py, tests/test_model_issue.py, tests/test_output_json.py, tests/test_output_xml.py
This PR also addresses a proper fix (in a number of places) for #153 as well as tackling #155.
=> feat: Complete support for `bom.components`

cyclonedx/model/bom_ref.py, cyclonedx/model/component.py, cyclonedx/model/service.py, cyclonedx/model/vulnerability.py, cyclonedx/output/serializer/json.py, cyclonedx/output/xml.py, tests/data.py, tests/fixtures/json/1.2/bom_services_complex.json, tests/fixtures/json/1.2/bom_services_nested.json, tests/fixtures/json/1.2/bom_services_simple.json, tests/fixtures/json/1.3/bom_services_complex.json, tests/fixtures/json/1.3/bom_services_nested.json, tests/fixtures/json/1.3/bom_services_simple.json, tests/fixtures/json/1.4/bom_services_complex.json, tests/fixtures/json/1.4/bom_services_nested.json, tests/fixtures/json/1.4/bom_services_simple.json, tests/fixtures/xml/1.2/bom_services_complex.xml, tests/fixtures/xml/1.2/bom_services_simple.xml, tests/fixtures/xml/1.3/bom_services_complex.xml, tests/fixtures/xml/1.3/bom_services_nested.xml, tests/fixtures/xml/1.3/bom_services_simple.xml, tests/fixtures/xml/1.4/bom_services_complex.xml, tests/fixtures/xml/1.4/bom_services_nested.xml, tests/fixtures/xml/1.4/bom_services_simple.xml, tests/test_model_component.py, tests/test_model_service.py, tests/test_model_vulnerability.py, tests/test_output_json.py, tests/test_output_xml.py
updated Vulnerability to also use new `BomRef` model
=> Continuation of #170 - missed updating Vulnerability to use `BomRef`

.pre-commit-config.yaml, CONTRIBUTING.md, docs/contributing.rst, docs/index.rst
Implementation for #190 
Fixes #190.
=> [DEV] Add pre-commit hooks

.gitattributes, cyclonedx/output/json.py, cyclonedx/schema/bom-1.2.xsd, cyclonedx/schema/bom-1.2b.schema.json, cyclonedx/schema/bom-1.3.xsd, cyclonedx/schema/bom-1.3a.schema.json, cyclonedx/schema/bom-1.4.xsd, tests/fixtures/json/1.2/bom_external_references.json, tests/fixtures/json/1.2/bom_services_complex.json, tests/fixtures/json/1.2/bom_services_nested.json, tests/fixtures/json/1.2/bom_services_simple.json, tests/fixtures/json/1.2/bom_setuptools.json, tests/fixtures/json/1.2/bom_setuptools_complete.json, tests/fixtures/json/1.2/bom_setuptools_with_cpe.json, tests/fixtures/json/1.2/bom_toml_1.json, tests/fixtures/json/1.2/bom_with_full_metadata.json, tests/fixtures/json/1.3/bom_external_references.json, tests/fixtures/json/1.3/bom_services_complex.json, tests/fixtures/json/1.3/bom_services_nested.json, tests/fixtures/json/1.3/bom_services_simple.json, tests/fixtures/json/1.3/bom_setuptools.json, tests/fixtures/json/1.3/bom_setuptools_complete.json, tests/fixtures/json/1.3/bom_setuptools_no_version.json, tests/fixtures/json/1.3/bom_setuptools_with_cpe.json, tests/fixtures/json/1.3/bom_toml_1.json, tests/fixtures/json/1.3/bom_with_full_metadata.json
Resolves #186.
**JSON**
Bump JSON schemas to latest fix version for 1.2 and 1.3 - see:
- https://github.com/CycloneDX/specification/issues/123
- https://github.com/CycloneDX/specification/issues/84
- https://github.com/CycloneDX/specification/issues/125
**XML**
Bump XML Schemas to latest fix version for version 1.2, 1.3 and 1.4 - see:
- https://github.com/CycloneDX/specification/issues/122
=> feat: Update CycloneDX Schemas to latest patch versions

tests/test_component.py
Fixes #228 
Signed-off-by: Rodney Richardson <rodney.richardson@cambridgeconsultants.com>
=> Don't hardcode component version in test

poetry.lock, pyproject.toml
=> Move types-setuptools and types-toml to dev dependencies

CHANGELOG.md
=> remove v3 from CHANGELOG #286

CONTRIBUTING.md
There's a difference between signing commits (-S) and signing off commits (-s).
=> docs: improve CONTRIBUTION instructions - sign-off step

docs/architecture.rst
noticed while reading the docs
=> docs: fix typo

deps.lowest.r, pyproject.toml, tox.ini
=> chore: prevent dev-lowest-lockfile from dependency bumps

deps.lowest.r, pyproject.toml
=> chore: clean unused def dependencies

.gitattributes, docs/examples.rst, docs/index.rst, examples/build_and_serialize.py
=> docs: add exaple how to build and serialize

examples/build_and_serialize.py
=> docs(example): showcase `LicenseChoiceFactory`

cyclonedx/output/__init__.py, cyclonedx/output/json.py, cyclonedx/output/xml.py, cyclonedx/schema/__init__.py, cyclonedx/schema/schema.py, tests/test_output.py, tests/test_output_json.py, tests/test_output_xml.py, tests/test_schema_SchemaVersion.py, tests/test_schema__res.py, tools/schema-downloader.py, tox.ini
=> proper enums

cyclonedx/output/__init__.py, cyclonedx/validation/__init__.py, cyclonedx/validation/json.py, cyclonedx/validation/xml.py, examples/complex.py, tests/test_validation.py, tests/test_validation_json.py, tests/test_validation_xml.py
=> feat: easy access validators

tests/_data/own/json/1.2/bom_with_mixed_licenses.json, tests/_data/own/json/1.3/bom_with_mixed_licenses.json, tests/_data/own/json/1.4/bom_with_mixed_licenses.json, tests/test_deserialize_json.py, tests/test_deserialize_xml.py
=> tests: import mixed licenses

pyproject.toml
=> docs: keywords & funding

.github/workflows/python.yml, .github/workflows/release.yml, pyproject.toml
fixes #525
fixes #435 as https://github.com/python-poetry/poetry/issues/8441 was included in poetry v1.8.0
=> build: use poetry v1.8.1

.github/workflows/release.yml, CHANGELOG.md, cyclonedx/__init__.py, docs/conf.py, pyproject.toml
=> chore: trusted publishing

README.md, docs/processes/release/conda-forge.md
- Fix few typos in conda-forge.md
- Removed unused PEP-508 ref in README.md
=> docs: Fix typos in in conda-forge.md and remove unused reference in README

.github/workflows/release.yml
=> chore: use 'python-semantic-release/publish-action'

.pre-commit-config.yaml
update precommit hook to match latest contribution guidelines.
=> chore: update precommit hook
